// Code generated by MockGen. DO NOT EDIT.
// Source: board_creation_service.go

// Package mock_services is a generated GoMock package.
package mock_services

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	boards "github.com/tonouchi510/application-arch-blueprint/circle-service/internal/domain/models/boards"
	circles "github.com/tonouchi510/application-arch-blueprint/circle-service/internal/domain/models/circles"
	shared "github.com/tonouchi510/application-arch-blueprint/circle-service/internal/domain/shared"
	db "github.com/tonouchi510/application-arch-blueprint/circle-service/internal/shared/db"
)

// MockIBoardCreationService is a mock of IBoardCreationService interface.
type MockIBoardCreationService struct {
	ctrl     *gomock.Controller
	recorder *MockIBoardCreationServiceMockRecorder
}

// MockIBoardCreationServiceMockRecorder is the mock recorder for MockIBoardCreationService.
type MockIBoardCreationServiceMockRecorder struct {
	mock *MockIBoardCreationService
}

// NewMockIBoardCreationService creates a new mock instance.
func NewMockIBoardCreationService(ctrl *gomock.Controller) *MockIBoardCreationService {
	mock := &MockIBoardCreationService{ctrl: ctrl}
	mock.recorder = &MockIBoardCreationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIBoardCreationService) EXPECT() *MockIBoardCreationServiceMockRecorder {
	return m.recorder
}

// CreateBoard mocks base method.
func (m *MockIBoardCreationService) CreateBoard(ctx context.Context, requesterId shared.UserId, circle circles.Circle, topic string, executor db.DbExecutor) (*boards.Board, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBoard", ctx, requesterId, circle, topic, executor)
	ret0, _ := ret[0].(*boards.Board)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBoard indicates an expected call of CreateBoard.
func (mr *MockIBoardCreationServiceMockRecorder) CreateBoard(ctx, requesterId, circle, topic, executor interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBoard", reflect.TypeOf((*MockIBoardCreationService)(nil).CreateBoard), ctx, requesterId, circle, topic, executor)
}
