// Code generated by SQLBoiler 4.19.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Boards            string
	CircleMembers     string
	CirclePermissions string
	Circles           string
	Posts             string
	Users             string
}{
	Boards:            "boards",
	CircleMembers:     "circle_members",
	CirclePermissions: "circle_permissions",
	Circles:           "circles",
	Posts:             "posts",
	Users:             "users",
}
