// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

type AddBoardPostInput struct {
	BoardID  uuid.UUID `json:"board_id"`
	CircleID uuid.UUID `json:"circle_id"`
	UserID   string    `json:"user_id"`
	Content  string    `json:"content"`
}

type AddCircleMemberInput struct {
	CircleID    uuid.UUID `json:"circle_id"`
	NewMemberID string    `json:"new_member_id"`
}

type BoardModel struct {
	ID         uuid.UUID `json:"id"`
	CircleUUID uuid.UUID `json:"circle_uuid"`
	Topic      string    `json:"topic"`
	Status     string    `json:"status"`
}

type ChangeBoardCreationPermissionInput struct {
	CircleID uuid.UUID `json:"circle_id"`
	Allowed  bool      `json:"allowed"`
}

type ChangeBoardStatusInput struct {
	BoardID   uuid.UUID `json:"board_id"`
	CircleID  uuid.UUID `json:"circle_id"`
	NewStatus int       `json:"new_status"`
}

type ChangeBoardTopicInput struct {
	BoardID  uuid.UUID `json:"board_id"`
	CircleID uuid.UUID `json:"circle_id"`
	NewTopic string    `json:"new_topic"`
}

type ChangeCircleDescriptionInput struct {
	CircleID       uuid.UUID `json:"circle_id"`
	NewDescription string    `json:"new_description"`
}

type ChangeCircleNameInput struct {
	CircleID uuid.UUID `json:"circle_id"`
	NewName  string    `json:"new_name"`
}

type CircleModel struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	OwnerID     string    `json:"owner_id"`
}

type CreateBoardInput struct {
	CircleID uuid.UUID `json:"circle_id"`
	Topic    string    `json:"topic"`
}

type CreateCircleInput struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type DelegateCircleOwnerInput struct {
	CircleID   uuid.UUID `json:"circle_id"`
	NewOwnerID string    `json:"new_owner_id"`
}

type DeleteBoardInput struct {
	BoardID  uuid.UUID `json:"board_id"`
	CircleID uuid.UUID `json:"circle_id"`
}

type DeleteCircleInput struct {
	CircleID uuid.UUID `json:"circle_id"`
}

type DeleteUserInput struct {
	UID string `json:"uid"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateUserAttributesInput struct {
	Name        *string `json:"name,omitempty"`
	Email       *string `json:"email,omitempty"`
	PhoneNumber *string `json:"phone_number,omitempty"`
	PhotoURL    *string `json:"photo_url,omitempty"`
}

type UserModel struct {
	ID            string  `json:"id"`
	Name          string  `json:"name"`
	Email         string  `json:"email"`
	EmailVerified bool    `json:"email_verified"`
	PhoneNumber   *string `json:"phone_number,omitempty"`
	PhotoURL      *string `json:"photo_url,omitempty"`
}
