// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	boards3 "github.com/tonouchi510/application-arch-blueprint/circle-service/internal/application/boards"
	circles3 "github.com/tonouchi510/application-arch-blueprint/circle-service/internal/application/circles"
	permissions2 "github.com/tonouchi510/application-arch-blueprint/circle-service/internal/application/permissions"
	users3 "github.com/tonouchi510/application-arch-blueprint/circle-service/internal/application/users"
	boards2 "github.com/tonouchi510/application-arch-blueprint/circle-service/internal/domain/models/boards"
	circles2 "github.com/tonouchi510/application-arch-blueprint/circle-service/internal/domain/models/circles"
	users2 "github.com/tonouchi510/application-arch-blueprint/circle-service/internal/domain/models/users"
	"github.com/tonouchi510/application-arch-blueprint/circle-service/internal/domain/services"
	"github.com/tonouchi510/application-arch-blueprint/circle-service/internal/infrastructure/firebase"
	"github.com/tonouchi510/application-arch-blueprint/circle-service/internal/infrastructure/firebase/users"
	"github.com/tonouchi510/application-arch-blueprint/circle-service/internal/infrastructure/sqlboiler/boards"
	"github.com/tonouchi510/application-arch-blueprint/circle-service/internal/infrastructure/sqlboiler/circles"
	"github.com/tonouchi510/application-arch-blueprint/circle-service/internal/infrastructure/sqlboiler/permissions"
	"github.com/tonouchi510/application-arch-blueprint/circle-service/internal/interface/graph"
)

// Injectors from wire.go:

// InitializeResolver initializes and returns a configured Resolver
func InitializeResolver() (*graph.Resolver, error) {
	client, err := firebase.NewFirebaseAuthClient()
	if err != nil {
		return nil, err
	}
	iUserRepository := users.NewUserRepository(client)
	iUserService := users2.NewUserService(iUserRepository)
	iUserApplicationService := users3.NewUserApplicationService(iUserRepository, iUserService)
	iCircleRepository := circles.NewCircleRepository()
	iCircleService := circles2.NewCircleService(iCircleRepository)
	iCirclePermissionRepository := permissions.NewCirclePermissionRepository()
	iCircleApplicationService := circles3.NewCircleApplicationService(iCircleService, iCircleRepository, iCirclePermissionRepository)
	iBoardRepository := boards.NewBoardRepository()
	iBoardDomainService := boards2.NewBoardDomainService(iBoardRepository)
	iBoardCreationService := services.NewBoardCreationService(iCirclePermissionRepository)
	iBoardApplicationService := boards3.NewBoardApplicationService(iBoardRepository, iCircleRepository, iBoardDomainService, iBoardCreationService)
	iCirclePermissionApplicationService := permissions2.NewCirclePermissionApplicationService(iCirclePermissionRepository, iCircleRepository)
	resolver := graph.NewResolver(iUserApplicationService, iCircleApplicationService, iBoardApplicationService, iCirclePermissionApplicationService)
	return resolver, nil
}
