package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"

	appboards "github.com/tonouchi510/application-arch-blueprint/circle-service/internal/application/boards"
	appcircles "github.com/tonouchi510/application-arch-blueprint/circle-service/internal/application/circles"
	apppermissions "github.com/tonouchi510/application-arch-blueprint/circle-service/internal/application/permissions"
	appusers "github.com/tonouchi510/application-arch-blueprint/circle-service/internal/application/users"
	"github.com/tonouchi510/application-arch-blueprint/circle-service/internal/interface/graph/model"
)

// UpdateUserAttributes is the resolver for the update_user_attributes field.
func (r *mutationResolver) UpdateUserAttributes(ctx context.Context, input model.UpdateUserAttributesInput) (*model.UserModel, error) {
	data, err := r.userApp.UpdateAttributes(ctx, appusers.UpdateUserAttributesCommand{
		Name:        input.Name,
		Email:       input.Email,
		PhotoUrl:    input.PhotoURL,
		PhoneNumber: input.PhoneNumber,
	})
	if err != nil {
		return nil, err
	}
	return toUserModel(*data), nil
}

// DeleteUser is the resolver for the delete_user field.
func (r *mutationResolver) DeleteUser(ctx context.Context, input model.DeleteUserInput) (bool, error) {
	if err := r.userApp.Delete(ctx, appusers.DeleteUserCommand{Uid: input.UID}); err != nil {
		return false, err
	}
	return true, nil
}

// CreateCircle is the resolver for the create_circle field.
func (r *mutationResolver) CreateCircle(ctx context.Context, input model.CreateCircleInput) (*model.CircleModel, error) {
	data, err := r.circleApp.Create(ctx, appcircles.CircleCreateCommand{
		Name:        input.Name,
		Description: input.Description,
	})
	if err != nil {
		return nil, err
	}
	return toCircleModel(*data)
}

// AddCircleMember is the resolver for the add_circle_member field.
func (r *mutationResolver) AddCircleMember(ctx context.Context, input model.AddCircleMemberInput) (bool, error) {
	if err := r.circleApp.AddMember(ctx, appcircles.CircleAddMemberCommand{
		CircleId:    input.CircleID.String(),
		NewMemberId: input.NewMemberID,
	}); err != nil {
		return false, err
	}
	return true, nil
}

// ChangeCircleName is the resolver for the change_circle_name field.
func (r *mutationResolver) ChangeCircleName(ctx context.Context, input model.ChangeCircleNameInput) (*model.CircleModel, error) {
	data, err := r.circleApp.ChangeName(ctx, appcircles.CircleChangeNameCommand{
		CircleId: input.CircleID.String(),
		NewName:  input.NewName,
	})
	if err != nil {
		return nil, err
	}
	return toCircleModel(*data)
}

// ChangeCircleDescription is the resolver for the change_circle_description field.
func (r *mutationResolver) ChangeCircleDescription(ctx context.Context, input model.ChangeCircleDescriptionInput) (*model.CircleModel, error) {
	data, err := r.circleApp.ChangeDescription(ctx, appcircles.CircleChangeDescriptionCommand{
		CircleId:       input.CircleID.String(),
		NewDescription: input.NewDescription,
	})
	if err != nil {
		return nil, err
	}
	return toCircleModel(*data)
}

// DelegateCircleOwner is the resolver for the delegate_circle_owner field.
func (r *mutationResolver) DelegateCircleOwner(ctx context.Context, input model.DelegateCircleOwnerInput) (*model.CircleModel, error) {
	data, err := r.circleApp.DelegateOwner(ctx, appcircles.CircleDelegateOwnerCommand{
		CircleId:   input.CircleID.String(),
		NewOwnerId: input.NewOwnerID,
	})
	if err != nil {
		return nil, err
	}
	return toCircleModel(*data)
}

// DeleteCircle is the resolver for the delete_circle field.
func (r *mutationResolver) DeleteCircle(ctx context.Context, input model.DeleteCircleInput) (bool, error) {
	if err := r.circleApp.Delete(ctx, appcircles.CircleDeleteCommand{
		CircleId: input.CircleID.String(),
	}); err != nil {
		return false, err
	}
	return true, nil
}

// CreateBoard is the resolver for the create_board field.
func (r *mutationResolver) CreateBoard(ctx context.Context, input model.CreateBoardInput) (*model.BoardModel, error) {
	data, err := r.boardApp.Create(ctx, appboards.BoardCreateCommand{
		CircleId: input.CircleID.String(),
		Topic:    input.Topic,
	})
	if err != nil {
		return nil, err
	}
	return toBoardModel(*data)
}

// ChangeBoardTopic is the resolver for the change_board_topic field.
func (r *mutationResolver) ChangeBoardTopic(ctx context.Context, input model.ChangeBoardTopicInput) (*model.BoardModel, error) {
	data, err := r.boardApp.ChangeTopic(ctx, appboards.BoardChangeTopicCommand{
		BoardId:  input.BoardID.String(),
		CircleId: input.CircleID.String(),
		NewTopic: input.NewTopic,
	})
	if err != nil {
		return nil, err
	}
	return toBoardModel(*data)
}

// ChangeBoardStatus is the resolver for the change_board_status field.
func (r *mutationResolver) ChangeBoardStatus(ctx context.Context, input model.ChangeBoardStatusInput) (*model.BoardModel, error) {
	data, err := r.boardApp.ChangeStatus(ctx, appboards.BoardChangeStatusCommand{
		BoardId:   input.BoardID.String(),
		CircleId:  input.CircleID.String(),
		NewStatus: input.NewStatus,
	})
	if err != nil {
		return nil, err
	}
	return toBoardModel(*data)
}

// AddBoardPost is the resolver for the add_board_post field.
func (r *mutationResolver) AddBoardPost(ctx context.Context, input model.AddBoardPostInput) (*model.BoardModel, error) {
	data, err := r.boardApp.AddNewPost(ctx, appboards.BoardAddPostCommand{
		BoardId:  input.BoardID.String(),
		CircleId: input.CircleID.String(),
		UserId:   input.UserID,
		Content:  input.Content,
	})
	if err != nil {
		return nil, err
	}
	return toBoardModel(*data)
}

// DeleteBoard is the resolver for the delete_board field.
func (r *mutationResolver) DeleteBoard(ctx context.Context, input model.DeleteBoardInput) (bool, error) {
	if err := r.boardApp.Delete(ctx, appboards.BoardDeleteCommand{
		BoardId:  input.BoardID.String(),
		CircleId: input.CircleID.String(),
	}); err != nil {
		return false, err
	}
	return true, nil
}

// ChangeBoardCreationPermission is the resolver for the change_board_creation_permission field.
func (r *mutationResolver) ChangeBoardCreationPermission(ctx context.Context, input model.ChangeBoardCreationPermissionInput) (bool, error) {
	if err := r.permissionApp.ChangeBoardCreationPermission(ctx, apppermissions.ChangeBoardCreationPermissionCommand{
		CircleId: input.CircleID.String(),
		Allowed:  input.Allowed,
	}); err != nil {
		return false, err
	}
	return true, nil
}

// Healthz is the resolver for the healthz field.
func (r *queryResolver) Healthz(ctx context.Context) (string, error) {
	return "ok", nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
