// File generated by `flutterfire configure`.
// This file should be used as a template for configuring Firebase in your Flutter app.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZDRPaRIdIdpKTYbpQeJNf_mMzNmPH2dI',
    appId: '1:415491777381:web:ea5998361c90abee3fb78c',
    messagingSenderId: '415491777381',
    projectId: 'application-arch-blueprint',
    authDomain: 'application-arch-blueprint.firebaseapp.com',
    storageBucket: 'application-arch-blueprint.firebasestorage.app',
  );

  // Android/iOS/macOSはFirebaseコンソールに実アプリ登録していないため、
  // apiKey/appIdはローカル開発(Auth Emulator接続)専用のダミー値。
  // Auth EmulatorはこれらをAPIキーとして検証しないため動作するが、実機配布や
  // 本番Firebaseに繋ぐ場合は`flutterfire configure`で実際の値に置き換えること。
  // projectIdだけはトークンのaud/iss検証に使われるため実プロジェクトIDに合わせている。
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'local-dev-only-android-api-key',
    appId: '1:415491777381:android:0000000000000000000000',
    messagingSenderId: '415491777381',
    projectId: 'application-arch-blueprint',
    storageBucket: 'application-arch-blueprint.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'local-dev-only-ios-api-key',
    appId: '1:415491777381:ios:0000000000000000000000',
    messagingSenderId: '415491777381',
    projectId: 'application-arch-blueprint',
    storageBucket: 'application-arch-blueprint.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'local-dev-only-macos-api-key',
    appId: '1:415491777381:ios:0000000000000000000001',
    messagingSenderId: '415491777381',
    projectId: 'application-arch-blueprint',
    storageBucket: 'application-arch-blueprint.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
